package com.salehhafyane.ecommerce.dto;

import com.salehhafyane.ecommerce.entity.Address;
import com.salehhafyane.ecommerce.entity.Order;
import com.salehhafyane.ecommerce.entity.OrderItem;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * Mapping contract for the checkout DTOs: fields must transfer 1:1 and
 * server-owned order state (status, tracking number) must never come from
 * the client payload.
 */
class OrderMapperTest {

    @Test
    void orderDtoMapsTotalsAndForcesPendingStatus() {
        OrderDTO dto = OrderDTO.builder()
                .totalQuantity(3)
                .totalPrice(new BigDecimal("300.00"))
                .build();

        Order order = OrderMapper.toEntity(dto);

        assertNotNull(order);
        assertEquals(3, order.getTotalQuantity());
        assertEquals(new BigDecimal("300.00"), order.getTotalPrice());
        assertEquals("PENDING", order.getStatus(), "Status is server-owned and must default to PENDING");
        assertNull(order.getOrderTrackingNumber(), "Tracking number must be generated by the service, not the DTO");
    }

    @Test
    void nullOrderDtoReturnsNull() {
        assertNull(OrderMapper.toEntity((OrderDTO) null));
    }

    @Test
    void addressDtoMapsFields() {
        AddressDTO dto = AddressDTO.builder()
                .city("Casablanca")
                .fullAddress("Boulevard Zero")
                .build();

        Address address = OrderMapper.toEntity(dto);

        assertNotNull(address);
        assertEquals("Casablanca", address.getCity());
        assertEquals("Boulevard Zero", address.getFullAddress());
        assertNull(address.getOrder(), "Address must not arrive with an order reference from the client");
    }

    @Test
    void nullAddressDtoReturnsNull() {
        assertNull(OrderMapper.toEntity((AddressDTO) null));
    }

    @Test
    void orderItemDtoMapsFields() {
        OrderItemDTO dto = OrderItemDTO.builder()
                .imageUrl("https://example.com/x.png")
                .unitPrice(new BigDecimal("49.99"))
                .quantity(5)
                .productId(9L)
                .build();

        OrderItem item = OrderMapper.toEntity(dto);

        assertNotNull(item);
        assertEquals("https://example.com/x.png", item.getImageUrl());
        assertEquals(new BigDecimal("49.99"), item.getUnitPrice());
        assertEquals(5, item.getQuantity());
        assertEquals(9L, item.getProductId());
        assertNull(item.getOrder(), "OrderItem must not arrive with an order reference from the client");
    }

    @Test
    void nullOrderItemDtoReturnsNull() {
        assertNull(OrderMapper.toEntity((OrderItemDTO) null));
    }
}
